<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NOTE: Align the .NET version with PowerShell 7.5. -->
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <EnableExpectoTestingPlatformIntegration>true</EnableExpectoTestingPlatformIntegration>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Collections.fs" />
    <Compile Include="Helper.fs" />
    <Compile Include="Data.fs" />
    <Compile Include="Mock.fs" />
    <Compile Include="Screen.fs" />
    <Compile Include="Keys.fs" />
    <Compile Include="Query.fs" />
    <Compile Include="Handle.fs" />
    <Compile Include="Pocof.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Expecto" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
    <!-- NOTE: for creating mock PSObject -->
    <PackageReference Include="Microsoft.PowerShell.SDK" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\pocof\pocof.fsproj"
                      Properties="TargetFramework=$(TestTargetFramework)"
                      Condition="'$(TestTargetFramework)' != ''" />
    <ProjectReference Include="..\pocof\pocof.fsproj"
                      Condition="'$(TestTargetFramework)' == ''" />
  </ItemGroup>

</Project>
