name: Snyk
description: Run Snyk to check for vulnerabilities in .NET projects and upload results to GitHub Code Scanning.

inputs:
  snyk_token:
    description: "Snyk token"
    required: true
  project_name:
    description: "Name of the .NET project to scan"
    required: true
  project_path:
    description: "Path to the .NET project to scan"
    required: true

runs:
  using: composite
  steps:
    - name: Run Snyk to check for vulnerabilities(${{ inputs.project_name }})
      uses: snyk/actions/dotnet@master
      # snyk/actions uses Container action that is only supported on Linux.
      if: runner.os == 'Linux'
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: ./src/${{ inputs.project_name }} --sarif-file-output=${{ inputs.project_name }}-snyk.sarif --org=krymtkts
    - name: Upload result to GitHub Code Scanning(${{ inputs.project_name }})
      if: runner.os == 'Linux'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.project_name }}-snyk.sarif
        category: Snyk(${{ inputs.project_name }})
