name: Snyk
description: Run Snyk to check for vulnerabilities in .NET projects and upload results to GitHub Code Scanning.

inputs:
  snyk_token:
    description: "Snyk token"
    required: true
  project_name:
    description: "Name of the .NET project to scan"
    required: true

runs:
  using: composite
  steps:
    - name: Run Snyk to check for vulnerabilities(${{ inputs.project_name }})
      continue-on-error: true # To make sure that SARIF upload gets called
      shell: bash
      run: |
        snyk test ./src/${{ inputs.project_name }} --sarif-file-output=${{ inputs.project_name }}-snyk.sarif --org=krymtkts
      env:
        SNYK_TOKEN: ${{ inputs.snyk_token }}
    - name: Upload result to GitHub Code Scanning(${{ inputs.project_name }})
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ inputs.project_name }}-snyk.sarif
        category: Snyk(${{ inputs.project_name }})
