name: Bump pslrm lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * 5"
      timezone: "Asia/Tokyo"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Update lockfile and create pull request
        uses: krymtkts/pslrm-bump-action@v0.0.2
        with:
          github-token: ${{ github.token }}
